# Generated by Django 4.1.7 on 2023-05-13 20:30

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_actor_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='Pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='don_argent',
            name='mode_paiement',
            field=models.CharField(choices=[('catre eldahabia', 'CARTE_DAHABIA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donateur',
            name='ccp_compte_num',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de compte CCP doit contenir 12 chiffres', regex='^\\d{12}$')]),
        ),
    ]
